apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
        default: latest
      environment:
        type: string
        required: true
        default: micro-hacker
env:
  APP_NAME: microhacker-auth
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        with:
          repository: jalts-808/j-hackers-auth
      - uses: cloudbees-days/setup-kubeconfig
        name: Set kubeconfig
        with:
          kubeconfig: ${{ secrets.kubeconfig }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: ${{ env.APP_NAME }}
          namespace: ${{ vars.namespace }}
          values: |
            image:
              repository: ${{ secrets.DOCKERHUB_USER }}/hackers-auth
              tag: ${{ inputs.artifactVersion }}
            hostname: hackers-auth.54.189.62.135.nip.io
            ingress:
              className: traefik
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: ${{ inputs.environment }}
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed environment
            [Auth endpoint](http://hackers-auth.54.189.62.135.nip.io/)
            Running hackers-auth:${{ inputs.artifactVersion }}
          format: MARKDOWN
